#%YAML

#All parameters should be in SI units

#Few parameters may be set to list of float or integer allowing to run successive simulation
# there are two syntaxes:
#       [x1, ..., xn] or range(start, end, step)
#       eg. range(0.02, 0.09, 0.02) or [0.02, 0.04, 0.06, 0.08] will give the same results
#       the parameter will take successively the values 0.02, 0.04, 0.06 and 0.08

archi:
    #if read_architecture is true then architecture will be constructed from the file(s) given by input_dir and input_file
    #otherwise the architecture will be generated according to the parameters
    read_architecture: True

    #Input architecture from scanned image (distance_from_base_(mm) \t lateral_root_length_(mm) \t order)
    #folder name
    input_dir: data/Arabido/

    #File name:
    #may be a list of names, eg. [file1, file2, file3] wildcar may be used
    input_file: [fabrice-test.txt]

#  [ 1045-sim-cut-n-flow-archi2.txt, 2020-01-19-9h06-cut-n-flow-archi2.txt,
#                  160316#2-cut-n-flow-archi2.txt, 200219-YBFB-Col-cut-n-flow-archi2.txt,
#                  200619-YBFB-Col-1-cut-n-flow-archi2.txt, 200619-YBFB-Col-2-cut-n-flow-archi2.txt,
#                  200702-YBFB-Col-1-cut-n-flow-archi2.txt, 200703-YBFB-Col-2-cut-n-flow-archi2.txt,
#                  200703-YBFB-Col-3-cut-n-flow-archi2.txt, 200721-YBFB-Col-2-correct-scale.txt,
#                  200724-YBFB-Col-1-cut-n-flow-archi2.txt, 15012020-1045-cut-n-flow-archi2.txt]
  
#  [200619-YBFB-e11-2-cut-n-flow-archi0.txt, 200619-YBFB-e15-1-cut-n-flow-archi0.txt,
#                 200619-YBFB-e15-2-cut-n-flow-archi2.txt, 200703-YBFB-e11-2-cut-n-flow-archi2.txt,
#                 200703-YBFB-e11-3-cut-n-flow-archi0.txt, 200703-YBFB-e11-4-cut-n-flow-archi0.txt,
#                 200703-YBFB-e15-3-cut-n-flow-archi2.txt, 200721-YBFB-e11-2-cut-n-flow-archi0.txt,
#                 200721-YBFB-e15-1-cut-n-flow-archi0.txt, 200721-YBFB-e15-2-cut-n-flow-archi0.txt,
#                 200721-YBFB-e15-5-cut-n-flow-archi0.txt, 200724-YBFB-e11-2-cut-n-flow-archi2.txt,
#                 200812-YBFB-e11-3-cut-n-flow-archi0.txt, 200812-YBFB-e15-1-cut-n-flow-archi0.txt,
#                 200812-YBFB-e15-3-cut-n-flow-archi2.txt]

    seed: 6973738

    #file names with length laws relative path
    #file format: "LR_length_mm" ; "relative_distance_to_tip"
    #laws used to generate lateral roots of the 1st order (1_order_law), and lateral roots of order above 1 (2_order_law)
    length_file:
        - data/length*order1*.csv
        - data/length*order2*.csv

    #length of the primary root
    #float or list of float
    #unit: m
    primary_length: 0.06 #range(0.15, 0.2, 0.01) # [0.04, 0.05, 0.06, 0.07, 0.08, 0.09]

    #branching delay
    #float or list of float
    #unit: m
    branching_delay: 1.0e-3 #range(1.0e-3, 3.0e-3, 0.25e-3) #[1.0e-3, 1.5e-3, 2.0e-3, 2.5e-3, 3.0e-3]

    #branching variability
    #float between [0 ; 1], 0.25 means 25%
    branching_variability: 0.25

    #maximum roots order
    order_max: 4

    #vertices length
    #unit: m
    segment_length: 1.0e-3

    #part of roots without any lateral root, distance from tip
    #float or list of float
    #unit: m
    nude_length: 0.005 #[0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035]  #0.02

    #reference radius of the primary root
    #float
    #unit: m
    ref_radius: 7.0e-5

    #radius decrease factor applied when increasing order
    #float
    #radius lateral order n: r = order_decrease_factor^n * ref_radius
    order_decrease_factor: 0.7

hydro:
    #radial conductivity
    #float
    #unit: microL/(s.MPa.m**2)
#    k0: 98.6 #219-col
#    k0: 327.6558 # K c-n-f 20-08-25, verified by FB 20/10/27
    k0: 602 # 703-col-2-Col
#    k0: 266.198 # 9h06 Col

    #axial_conductance_data
    #   - [x1, ......, xn]
    #   - [K1, ....., Kn]
    #list of float
    #unit: microL.m/(s.Mpa)
    axial_conductance_data:
#        - [0, 0.2]
#        - [2.0e-4, 2.0e-4]
        - [0, 1.5e-2, 4.0e-2, 6.0e-2, 7.65e-2, 9.65e-2, 11.75e-2, 14.85e-2, 19.75e-2]
#        - [2.90E-05, 1.24E-04, 1.77E-03, 2.18E-03, 1.83E-03, 3.05E-03, 4.19E-03, 3.45E-03, 2.60E-03] # lowess Poiseuille
        - [ 3.24E-05, 2.99E-04, 3.90E-04, 3.53E-04, 3.98E-04, 7.23E-04, 9.16E-04, 8.36E-04, 4.36E-04] # K c-n-f 20-08-25, verified by FB 20/10/27
#        - [ 1.27379472363e-07, 6.13251834993e-07, 7.49252297474e-05, 0.000151296908088, 0.000241835642959,
#            0.000451867369451, 0.000681121043037, 4.2065861201e-05, 0.000374574363991] # 219-Col
#        - [0.000225365133957, 0.000361018671829, 0.000373458306021, 0.000374530640718, 0.000445524008713,
#           0.00252105545618, 0.00350046937138, 0.00274728894503, 0.00128187837883] #703-col-2
#        - [ 0.000141339319186, 0.000330724891721, 0.000306685275821, 0.000150126759557, 1.43506973613e-05,
#            0.000155128795961, 0.000294243239469] # 9h06 Col


solute:
    #J_s: active pumping rate
    #float
    #unit: mol/(m2.s)
    J_s: 1.0e-20

    #P_s: permeability coefficient
    #float
    #unit: m/s
    P_s: 1.0e-20

    #Cse: concentration of permeating solutes
    #float
    #unit: mol/m3 or mM
    Cse: 0. #19.96 -> pi CTR = -0.034 MPa

    #Ce: concentration of non-permeating solutes
    #float
    #unit: mol/m3 or mM
    Ce: 0. #116.14 # pi 150 PEG = -0.332 MPa => 116.14 (according to Cse=19.96)

    #sigma: reflexion coefficient
    #float
    #dimensionless
    Sigma: 1.

experimental:
    #water flux at the root base
    #float
    #unit: microL/s
    Jv:  1.00e-3

    #hydric potential outside the roots (pressure chamber)
    #float
    #unit: MPa
    psi_e: 0.401325

    #hydric potential at the root base (e.g. atmospheric pressure for decapitated plant)
    #float
    #unit: MPa
    psi_base: .101325

output:
    #distance from the base for intercepts calculation
    # float or list of float
    #unit: m
    intercepts: []

    #factor to explore a k0 range
    # float or list of float
    radfold: 1. #range(0.125,2.125,0.125) #range(1.5, 0.5, -0.01) #[10., 92., 200.] #range(0.1, 1.1, 0.1) #1.

    #like radfold but apply to axial_conductance_data
    axfold: 1. #range(1, 0.04, -0.05)

    #number of run with the same set of parameters i.e. number of different seeds
    #integer
    #enable only if read_architecture is false
    run_nb: 1
