name: hydroroot
channels:
  - conda-forge
  - openalea3
dependencies:
  # list here manually conda-only deps (listed in [tool.conda.environment] section of pyproject)
  - python
  - pip
  - openalea.mtg
  - openalea.plantgl
  - oawidgets
  - yaml
  - rsml
  # let pip install the rest using pyproject.toml (if you are okay with conda/pip mix)
  - pip:
      - -e .."[doc, test]"