{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: {{PYTHON}} -m pip install . -vv

requirements:
  build:
    - python {{ pyproject["project"]["requires-python"] }}
    {% for dep in pyproject["build-system"]["requires"] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python {{ pyproject["project"]["requires-python"] }}
    {% for dep in pyproject["project"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in pyproject["tool"]["conda"]["environment"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - pytest

  imports:
    - openalea.hydroroot

  source_files:
    - test/**
    - test/data/**
  commands:
    - cd test
    - pytest -v

about:
  summary: {{ pyproject["project"]["description"] }}
  license: {{ pyproject["project"]["license"] }}
  home: {{ pyproject["project"]["urls"]["Homepage"] }}

