name: hydroroot
channels:
  - conda-forge
  - openalea3
dependencies:
  - openalea.deploy
  - openalea.mtg
  - openalea.plantgl
  - pandas
  - matplotlib
  - numpy
  - scipy
  - yaml
  - pyyaml
  - rsml
  - sphinx-favicon
  - sphinx-rtd-theme
  - nbsphinx
  - myst-parser
  - pydata-sphinx-theme
  - pip
  - pip:
    - -e ..
