name: hydroroot
channels:
  - conda-forge
  - openalea3
dependencies:
  - openalea.mtg
  - openalea.plantgl
  - openalea.deploy
  - pandas
  - matplotlib
  - numpy
  - scipy
  - yaml
  - pyyaml
  - rsml
  - pydata-sphinx-theme
  - pip
  - pip:
    - -e ..[doc]
