name: Building Package

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@20-python-313-numpy
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}